# Generated by Django 2.2.5 on 2019-09-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(max_length=2500, null=True)),
                ('previous_name', models.CharField(max_length=100, null=True)),
                ('site_location', models.CharField(max_length=100, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('type_of_site', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('designer', models.CharField(max_length=50, null=True)),
                ('listed_structures', models.CharField(max_length=150, null=True)),
                ('borough', models.CharField(max_length=30, null=True)),
                ('site_ownership', models.CharField(max_length=50, null=True)),
                ('site_management', models.CharField(max_length=50, null=True)),
                ('open_to_public', models.CharField(max_length=10, null=True)),
                ('opening_times', models.CharField(max_length=30, null=True)),
                ('special_conditions', models.CharField(max_length=250, null=True)),
                ('facilities', models.CharField(max_length=250, null=True)),
                ('public_transportation', models.CharField(max_length=200, null=True)),
                ('lon_lat', models.CharField(max_length=100, null=True)),
                ('lon', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('grid_reference', models.CharField(max_length=30, null=True)),
                ('size_in_hectares', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=250, null=True)),
                ('fuller_information', models.TextField(max_length=10000, null=True)),
                ('sources_consulted', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
