# Generated by Django 3.0.8 on 2020-07-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxit', '0002_auto_20200714_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='borough',
            field=models.CharField(max_length=50, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.CharField(max_length=30, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='designer',
            field=models.CharField(max_length=50, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='facilities',
            field=models.CharField(max_length=250, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='fuller_information',
            field=models.TextField(max_length=20000, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='grid_reference',
            field=models.CharField(max_length=36, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.CharField(max_length=250, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='listed_structures',
            field=models.CharField(max_length=150, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon_lat',
            field=models.CharField(max_length=100, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='open_to_public',
            field=models.CharField(max_length=10, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='opening_times',
            field=models.CharField(max_length=30, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(max_length=10, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='previous_name',
            field=models.CharField(max_length=100, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='public_transportation',
            field=models.CharField(max_length=200, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='site_location',
            field=models.CharField(max_length=100, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='site_management',
            field=models.CharField(max_length=50, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='site_ownership',
            field=models.CharField(max_length=50, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='size_in_hectares',
            field=models.CharField(max_length=100, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='sources_consulted',
            field=models.TextField(max_length=1000, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='special_conditions',
            field=models.CharField(max_length=250, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='summary',
            field=models.TextField(max_length=2500, null=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_of_site',
            field=models.CharField(max_length=50, null=''),
        ),
    ]
